# Root-level Netlify config to delegate build to subdirectory
[build]
  base = "fpj-storytelling"
  publish = "fpj-storytelling/build"
  command = "npm run build"

# Mirror SPA redirect at root level (Netlify will merge with subdir file if present; root takes precedence)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
