# Netlify configuration
[build]
  publish = "build"
  command = "npm run build"

# Ensure SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security & privacy headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # NOTE: A full Content-Security-Policy can be added later after auditing external resources.
    # Example (in progress; DO NOT enable until scripts/styles/fonts fully enumerated):
    # Content-Security-Policy = "default-src 'self'; script-src 'self' https://plausible.io; img-src 'self' data: https://plausible.io; style-src 'self' 'unsafe-inline'; connect-src 'self' https://plausible.io; font-src 'self' data:;"
